version: '3.8'
services:
  app:
    build: .
    image: cyberkat7217/calc_web_app:1.1.1
    ports:
      - '3043:3040'
    environment:
      - PORT=3043
    container_name: my-app4
    networks:
      - my-bridge-network1

  app1:
    build: .
    image: cyberkat7217/calc_web_app:1.1.1
    ports:
      - '3044:3040'
    environment:
      - PORT=3044
    container_name: my-app3
    networks:
      - my-bridge-network1
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f","http://localhost3044"]
      interval: 1s

networks:
  my-bridge-network1:
    driver: bridge